name: Compatibility Build

on:
  schedule:
    - cron: '5 6 * * *'

jobs:
  integration:
    strategy:
      matrix:
        profile: ['3.0.4-SNAPSHOT', '3.1.0-SNAPSHOT']
    name: Build against Boot ${{ matrix.profile }}
    runs-on: ubuntu-latest

    steps:

    - name: Check out sources
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Build with Maven
      run: ./mvnw -B -Pwith-preview-repos -Dspring-boot.version=${{ matrix.version }}
